### ISSUE TITLE
Is this  line in preprocess.py wrong ? " fold_label.append(np.eye(5)[label]) "

### ISSUE THREAD

**Issue by xdjwolf** [ziyujia/MSTGCN#1]
I run   python3 preprocess.py , but when come to `  fold_label.append(np.eye(5)[label])`  this line, come up with a run error.

IndexError: index 5 is out of bounds for axis 0 with size 5

**Comment by ziyujia** [comment]
We have fixed this bug. It is caused by REM being marked '5' in the ISRUC-S3 dataset.
Thank you for your feedback.
