### ISSUE TITLE
Distance Matrix for the MASS SS3 dataset

### ISSUE THREAD

**Issue by MathieuSeraphim** [ziyujia/MSTGCN#7]
I would like to run your MSTGCN code for the MASS SS3 dataset. However, a critical piece of information is missing: the distance matrix for the 26 EEG signals of this dataset.
Not knowing how you created it in the first place (it has not been detailed in your paper), I am unable to run your code on MASS SS3.

Could you provide the distance matrix for this dataset?

**Comment by NingXJ1999** [comment]
The distance between electrodes is calculated by the Euclidean distance between the electrodes, which can be achieved by 2D or 3D coordinates.

Based on a distance matrix, after normalizing all distances, use the following equation to calculate the weight of each edge:
![distance-based](https://user-images.githubusercontent.com/42231551/195240205-98ca6e19-e11a-4e7d-aaea-80dc0b50286a.svg)
where \gamma is a sparsity factor and d_{i,j} is the normalized distance between node i and node j. Finally, the Softmax function can be used to normalize A^{DC}.

---

The attachment is the spatial distance based matrix we use for MASS-SS3. For MASS-SS3 dataset, we recalibrate all EEG data to the Cz channel (-Cz), so the final number of channels is 25. The distance between electrodes is manually assigned based on relative Euclidean distance. The distances between EEG/EOG and EMG/ECG use the average distance of EEG/EOG pairs. The order of the channels corresponding to this matrix is as follows:

| channel id   |  1   |  2   |  3   |  4   |  5   |  6   |  7   |  8   |  9   |  10  |  11  |  12  |  13  |
| :----------: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: |
| channel name | FP1  | FP2  |  Fz  |  F3  |  F4  |  F7  |  F8  |  C3  |  C4  |  T3  |  T4  |  Pz  |  P3  |
| channel id   |  14  |  15  |  16  |  17  |  18  |  19  |  20  |  21  |  22  |  23  |  24  |  25  |      |
| channel name |  P4  |  T5  |  T6  |  Oz  |  O1  |  O2  | EogL | EogR | Emg1 | Emg2 | Emg3 | Ecg  |      |

[DistanceMatrix_MASS.zip](https://github.com/ziyujia/MSTGCN/files/9761123/DistanceMatrix_MASS.zip)

**Comment by MathieuSeraphim** [comment]
Thanks!
